In [11]:
%load_ext autoreload
%autoreload 2


import numpy as np

import torch
from torch_ga import GeometricAlgebra
from torch_ga.clifford.algebra import CliffordAlgebra

from icecream import ic
# ic = print

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
import torch_ga
print(torch_ga.__version__)

0.0.9


In [13]:
ga = GeometricAlgebra([1, 1, -1])
cl = CliffordAlgebra([1, 1, -1])

ga = ga.to('cuda')
cl = cl.to('cuda')

In [27]:
a = ga.embed(torch.tensor([3.,5.]),(3,4)).to('cuda')
b = ga.embed(torch.tensor([2.,1.]),(3,4)).to('cuda')

c = ga.embed_grade(torch.tensor([1., 2., 3.]),1).to('cuda')


ic(ga(a),ga(b),ga(c))

ga.get(a,(3,4))



ic(ga.get_scalar(a))
ic(ga.get_vector(a))
ic(ga.get_pseudo_scalar(a))
ic(ga.get_pseudo_vector(a))
ic(ga.get_blade(a,0))
ic(ga.get_blade(a,1))
ic(ga.get_blade(a,2))
ic(ga.get_blade(a,3))

ic(ga.get_grade(a,0))
ic(ga.get_grade(a,1))
ic(ga.get_grade(a,2))

ic| ga(a): 3e2 + 5e01, ga(b): 2e2 + 1e01, ga(c): 1e0 + 2e1 + 3e2
ic| ga.get_scalar(a): tensor(0., device='cuda:0')
ic| ga.get_vector(a): tensor([0., 0., 3.], device='cuda:0')
ic| ga.get_pseudo_scalar(a): tensor(0., device='cuda:0')
ic| ga.get_pseudo_vector(a): tensor([5., 0., 0.], device='cuda:0')
ic| ga.get_blade(a,0): tensor([0.], device='cuda:0')
ic| ga.get_blade(a,1): tensor([0., 0., 3.], device='cuda:0')
ic| ga.get_blade(a,2): tensor([5., 0., 0.], device='cuda:0')
ic| ga.get_blade(a,3): tensor([0.], device='cuda:0')
ic| ga.get_grade(a,0): tensor([0.], device='cuda:0')
ic| ga.get_grade(a,1): tensor([0., 0., 3.], device='cuda:0')
ic| ga.get_grade(a,2): tensor([5., 0., 0.], device='cuda:0')


tensor([5., 0., 0.], device='cuda:0')

In [26]:
a = cl.embed(torch.tensor([3.,5.]),(3,4)).to('cuda')
b = cl.embed(torch.tensor([2.,1.]),(3,4)).to('cuda')

c = cl.embed_grade(torch.tensor([1., 2., 3.]),1).to('cuda')

ic(a)
ic(b)
ic(c)
print(cl.product(a,b),cl.inner_product(a,b),cl.outer_product(a,b),cl.norm(a))


ic(cl.get_scalar(a))
ic(cl.get_vector(a))
ic(cl.get_pseudo_scalar(a))
ic(cl.get_pseudo_vector(a))
ic(cl.get_blade(a,0))
ic(cl.get_blade(a,1))
ic(cl.get_blade(a,2))
ic(cl.get_blade(a,3))

ic(cl.get_grade(a,0))
ic(cl.get_grade(a,1))
ic(cl.get_grade(a,2))


a = cl(a).to('cuda')
b = cl(b).to('cuda')
ic(a.tensor.device)

ic(b.tensor.device)

ic(a)
ic(b)

ic(a,b,a*b,a|b, a^b)

ga.norm(a.tensor)

tensor([ 11.,   0.,   0.,   0.,   0.,   0.,   0., -13.], device='cuda:0') tensor([ 11.,   0.,   0.,   0.,   0.,   0.,   0., -13.], device='cuda:0') tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0') tensor([4.], device='cuda:0')


ic| a: tensor([0., 0., 0., 3., 5., 0., 0., 0.], device='cuda:0')
ic| b: tensor([0., 0., 0., 2., 1., 0., 0., 0.], device='cuda:0')
ic| c: tensor([0., 1., 2., 3., 0., 0., 0., 0.], device='cuda:0')
ic| cl.get_scalar(a): tensor(0., device='cuda:0')
ic| cl.get_vector(a): tensor([0., 0., 3.], device='cuda:0')
ic| cl.get_pseudo_scalar(a): tensor(0., device='cuda:0')
ic| cl.get_pseudo_vector(a): tensor([5., 0., 0.], device='cuda:0')
ic| cl.get_blade(a,0): tensor([0.], device='cuda:0')
ic| cl.get_blade(a,1): tensor([0., 0., 3.], device='cuda:0')
ic| cl.get_blade(a,2): tensor([5., 0., 0.], device='cuda:0')
ic| cl.get_blade(a,3): tensor([0.], device='cuda:0')
ic| cl.get_grade(a,0): tensor([0.], device='cuda:0')
ic| cl.get_grade(a,1): tensor([0., 0., 3.], device='cuda:0')
ic| cl.get_grade(a,2): tensor([5., 0., 0.], device='cuda:0')
ic| a.tensor.device: device(type='cuda', index=0)
ic| b.tensor.device: device(type='cuda', index=0)
ic| a: 3e2 + 5e01
ic| b: 2e2 + 1e01
ic| a: 3e2 + 5e01
    b: 2e2 + 1

tensor(5.8310, device='cuda:0')

In [6]:
ga.get_scalar(a)

tensor(0., device='cuda:0')

In [26]:
a = ga.e_ + ga.e0 + ga.e1
b = -ga.e_ + ga.e01 

print(cl.product(a,b),cl.inner_product(a,b)+cl.outer_product(a,b))

ic(cl.product(a,b),cl.inner_product(a,b),cl.outer_product(a,b))



tensor([-1., -2.,  0.,  0.,  1.,  0.,  0.,  0.], device='cuda:0') tensor([-1., -3.,  1.,  0.,  1.,  0.,  0.,  0.], device='cuda:0')
tensor([-1., -2.,  0.,  0.,  1.,  0.,  0.,  0.], device='cuda:0') tensor([-1., -2.,  0.,  0.,  1.,  0.,  0.,  0.], device='cuda:0') tensor([ 0., -1.,  1.,  0.,  0.,  0.,  0.,  0.], device='cuda:0')
