In [28]:
%load_ext autoreload
%autoreload 2


import numpy as np

import torch
from torch_ga import GeometricAlgebra
from torch_ga.clifford.algebra import CliffordAlgebra

# from icecream import ic
ic = print

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [29]:
import torch_ga
print(torch_ga.__version__)

0.0.7


In [30]:
ga = GeometricAlgebra([1, 1, -1])
cl = CliffordAlgebra([1, 1, -1])

ga = ga.to('cuda')
cl = cl.to('cuda')

In [37]:
a = ga.embed(torch.tensor([3.,5.]),(3,4)).to('cuda')
b = ga.embed(torch.tensor([2.,1.]),(3,4)).to('cuda')
ic(ga(a),ga(b))

ga.get(a,(3,4))

3e2 + 5e01 2e2 + 1e01


tensor([3., 5.], device='cuda:0')

In [35]:
a = cl.embed(torch.tensor([3.,5.]),(3,4)).to('cuda')
b = cl.embed(torch.tensor([2.,1.]),(3,4)).to('cuda')
ic(a)
ic(b)
print(cl.product(a,b),cl.inner_product(a,b),cl.outer_product(a,b))

a = cl(a).to('cuda')
b = cl(b).to('cuda')
ic(a.tensor.device)

ic(b.tensor.device)

ic(a)
ic(b)

ic(a,b,a*b,a|b, a^b)

tensor([0., 0., 0., 3., 5., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 2., 1., 0., 0., 0.], device='cuda:0')
tensor([ 11.,   0.,   0.,   0.,   0.,   0.,   0., -13.], device='cuda:0') tensor([ 11.,   0.,   0.,   0.,   0.,   0.,   0., -13.], device='cuda:0') tensor([0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
cuda:0
cuda:0
3e2 + 5e01
2e2 + 1e01
3e2 + 5e01 2e2 + 1e01 -11 + 13e012 -11 13e012


In [26]:
a = ga.e_ + ga.e0 + ga.e1
b = -ga.e_ + ga.e01 

print(cl.product(a,b),cl.inner_product(a,b)+cl.outer_product(a,b))

ic(cl.product(a,b),cl.inner_product(a,b),cl.outer_product(a,b))



tensor([-1., -2.,  0.,  0.,  1.,  0.,  0.,  0.], device='cuda:0') tensor([-1., -3.,  1.,  0.,  1.,  0.,  0.,  0.], device='cuda:0')
tensor([-1., -2.,  0.,  0.,  1.,  0.,  0.,  0.], device='cuda:0') tensor([-1., -2.,  0.,  0.,  1.,  0.,  0.,  0.], device='cuda:0') tensor([ 0., -1.,  1.,  0.,  0.,  0.,  0.,  0.], device='cuda:0')
